### PR TITLE
Add additional dataviz

### LINKED ISSUE #68: Display funding allocation across general areas
## Issue we're trying to solve

We have a [long list of questions](https://docs.google.com/spreadsheets/d/1vRBUhrAR3d05cNq9SDKmU0xytxYq5Nv9bXPKGP32XzI/edit?usp=sharing) we'd like the website to answer, based on our initial consultations with the SSOC (Measure Z oversight commission). One of our priority questions includes:

- How is the money allocated? 
  - To coordinating agencies (OPD, DVP, OFD, admin)?
  - To MZ strategy areas (adult life coaching, youth life coaching, etc)?
  - To individual programs?

Current data inventory docs:

- [List of funded programs](https://docs.google.com/spreadsheets/d/1yAhVQlh8SRbU5ATOnuXoxvDPSY1zZ-DPojKGZDmIG1M/edit?usp=sharing)
- [List of evaluation reports and data extraction from them](https://docs.google.com/spreadsheets/d/1DAgFct6BsR3vwoKfSyz-bY733Pdh8sd1goV4bs98aGM/edit?usp=sharing)

### The to-do
Explore different ways to display this data on the site. Some considerations:
- Interactive vs static?
- Color use
- Cumulative vs. by year
- Accessibility attributes
- Relativity and comparisons

### PR DESCRIPTION
**Pull request by theecrit**
Closes #68:
- Adds agency spending chart
- Adds program spending chart
- Separates spending dataviz into a new "Spending" page

These charts leave a lot to be desired in terms of usability and overall design. I'll open a new issue for some UX work. :)

Screenshot 2022-02-16 at 15-24-26 Spending

### CODE REVIEW

**Review by aemann2 — CHANGES_REQUESTED** [review]
Hey @theecrit  -- the changes look good, but it looks like there's an issue with package-lock.json getting a bunch of lines removed. I noticed this in a previous commit -- for some reason, it looks like you have an older version of this file. Could you try deleting your package-lock.json file for this branch, then running `npm install` again for this branch and then pushing those changes? Also, could you make sure your `main` branch is up to date, then delete package-lock.json and run `npm install` again on that branch as well? 

Something must have gotten out of sync somehow, and I'm thinking this should fix the problem where there are a bunch of lines getting removed from package-lock.json in some PRs.

**Comment by theecrit** [comment]
@aemann2 Thanks for that — I'm not sure why this is happening (it's not the first time). When I delete the package-lock file and then re-install npm, it rebuilds the package-lock file as `"lockfileVersion": 1`. My googling hasn't turned up a fix. When I run `npm install`, I get:

```
jbook2@jBook2 funding-public-safety % npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN funding-public-safety@1.0.0 license should be a valid SPDX license expression

audited 439 packages in 1.441s

25 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
jbook2@jBook2 funding-public-safety % 
```

And the package-lock.json file generated contains` "lockfileVersion": 1,`. 🤔

**Comment by theecrit** [comment]
Still can't figure out how to get npm to install `lockfileVersion` as v2. 😞

**Comment by aemann2** [comment]
Hey @theecrit, good catch! There are so many little things that can get out of sync. I'm still seeing that the package-lock file is taking out a bunch of lines (looks like over 4k), so I think what I'll do is open a PR of my own, merge this one in to that without the package-lock changes, and then merge that one into the main. 

I'm also planning on making a PR today to remove the `docs` file from tracking. Maybe after that gets merged, you might try downloading a fresh copy of the repo and running `npm install` on that? That should put you even, and we should stop seeing the removed lines in package-lock.

**Review by aemann2 — APPROVED** [review]

**Pull request merged**
